### ISSUE TITLE
Setting DRAT_REPOS does not install the latest available package version, as bspm is enabled by default

### ISSUE THREAD

**Issue by jranke** [eddelbuettel/r-ci#10]
After an odyssee of attempts to check my pfm package on Travis, I finally ended up with

```
install:
  - ./run.sh install_all
  - ./run.sh install_r drat
  - Rscript -e 'bspm::disable(); drat::addRepo("jranke"); install.packages("mkin")'
```

Simply setting DRAT_REPOS did not do the trick, because
- the drat package has to be installed
- the use of bspm, which is the default, prevents installing the latest version available in the drat repo

I think it would be nice to install the drat package automatically if DRAT_REPOS is set.

Not pulling the latest version although it is available in an alternative repo is likely a bug in bspm, or am I missing something?

**Comment by jranke** [comment]
OK, we can skip installing the drat package, I now have

```
env:
  DRAT_REPOS: "jranke"
```

and

```
install:
  - ./run.sh install_all
  - Rscript -e 'bspm::disable(); install.packages("mkin")'
```
to install the latest version from drat. So basically using bspm interferes with installing the latest version from drat.

**Comment by eddelbuettel** [comment]
Hi @jranke yes that sounds like something I should indeed carry down into `r-ci` (at least when `bspm` use in effect on, which is now the default).  I get bitten by this every now and then too with `r2u` binaries taking precedence over source so that sometimes sources are ignore.  The (local to the call) `bspm::disable` should do the trick.

Sorry about the trouble. I am otherwise quite pumped how well r2u works in r-ci though.

(Looks at code)

Ah damn.  Because we use the `drat` repo to enlarge the set of (R) repos:

```r
SetRepos() {
    echo "local({" >> ~/.Rprofile
    echo "   r <- getOption(\"repos\");" >> ~/.Rprofile
    echo "   r[\"CRAN\"] <- \"${CRAN}\"" >> ~/.Rprofile
    for d in ${DRAT_REPOS}; do
        echo "   r[\"${d}\"] <- \"https://${d}.github.io/drat\"" >> ~/.Rprofile
    done
    echo "   options(repos=r)" >> ~/.Rprofile
    echo "})" >> ~/.Rprofile
}
```

but then later rely on `bspm` to do magic we effectively negate the `drat` (source) repo.  Not great.  Not sure I can do something to restore the full `drat` (source repo for as Linuxers) now that `r2u` is here.  Unless maybe if one turns `bspm` off but we do not want that.

/cc @enchufa2  Any idea about how to 'magically' elevate the importance of certain R source repos?  Would be nice if we had 'repo pinning' but we don't so ... :-/

**Comment by Enchufa2** [comment]
Idea 1, at package level:

```r
# we start with bspm enabled
install.packages("pkg1") # bspm tries to install binaries
install.packages(I("pkg2")) # bspm doesn't take effect
```

At repo level, we would need to set some flag, and bspm would need to check for its presence, then query the available packages in the repos with that flag, and finally do nothing for packages that match those.

**Comment by jranke** [comment]
> Sorry about the trouble. I am otherwise quite pumped how well r2u works in r-ci though.

No worries - r-ci is nice, it lets me keep using travis although the semi-official R support ceased, which I like because I like having alternatives to an all-github solution.

**Comment by jranke** [comment]
> At repo level, we would need to set some flag, and bspm would need to check for its presence, then query the available packages in the repos with that flag, and finally do nothing for packages that match those.

Wouldn't it be possible to retrieve the R package versions from the binary repo, and let `install.package()` decide to used the latest version (as it does without bspm enabled)?

**Comment by eddelbuettel** [comment]
> Wouldn't it be possible to retrieve the R package versions from the binary repo, and let install.package() decide to used the latest version (as it does without bspm enabled)?

I sometimes muse about this too.  Or maybe a filter in front of `remotes`?  Something is not quite how we like it but I have not distilled out what.  Maybe we do indeed to 'filter' the available packages and offer two stages (at least optionally).  (It gets ever murkier if you also add `type="binary"` to the mix, I had a working drat repo ignored under CI yesterday when I tried windoze so i needed two stages to first produce a binary of the dependency that I then stuck into the drat...)

**Comment by Enchufa2** [comment]
BTW, this can be closed.

**Comment by jranke** [comment]
Hi @eddelbuettel and @Enchufa2, I still have to disable bspm temporarily in my travis config in order to have precedence of the more recent version (of deSolve 1.35 in this case) over the CRAN version (1.34). I have trouble parsing the build logs, but the fact is that without disabling bspm for installing deSolve my build failed:
https://app.travis-ci.com/github/jranke/mkin/builds/260772083
and after using the workaround described above, it passes:
https://app.travis-ci.com/github/jranke/mkin/jobs/596286875
The change in the travis config:
https://github.com/jranke/mkin/commit/9d6e7920f93c4a2da75ecf053ca2691b91dbafe8

**Comment by Enchufa2** [comment]
This is with a current version of bspm:

```r
> drat::addRepo("jranke")
> install.packages("deSolve")
--- Please select a CRAN mirror for use in this session ---
Available system packages...

  There is a binary version available but the source version is later:
        binary source
deSolve   1.34   1.35

Do you prefer later versions from sources? (Yes/no/cancel)
```

So maybe bspm is not up-to-date or the "fast" mode is enabled in r-ci, which effectively bypasses this feature.

**Comment by Enchufa2** [comment]
Maybe the workaround for eddelbuettel/r2u/issues/29 was the cause for this one? I think that it's best to avoid enabling the fast mode by default in the r2u images.

**Comment by Enchufa2** [comment]
Sorry, I thougth that r-ci was using r2u images, but it's not (anyway, the PR above and a rebuild still makes sense).

The regression in r-ci was introduced here after enabling "binary-source" installation, which bypasses version checks: https://github.com/eddelbuettel/r-ci/commit/d104afaba5ab3069ea0e3ab4a200c657b892062a

**Comment by eddelbuettel** [comment]
No r-ci is just a script but this is another nice illustration how things can go sour when we a) enable bspm globally (which is what we want), b) enable fast mode (which is what we want) and c) suffer from side effects as we were foolish enough to conflate the fast mode setting with one for R.

Part of it is me, @jranke, because of b).  The easiest short term fix is another command injected in your CI to (essentially) do

      bspm::disable(); install.packages("pkgname", repos=..., type="source")

We hope to have that straightened soon. I run lots of r-ci.sh jobs (at GitHub) myself each day.

**Comment by Enchufa2** [comment]
I suggest to make this configurable. E.g. `USE_BSPM_VERSION_CHECK` or similar. Otherwise, we addressed this for nothing. ;)

**Comment by eddelbuettel** [comment]
Yes.  Enabling a drat repo is already configurable in r-ci.

But you are running around furiously in different places, changes at multiple repo, sending PRs I didn't ask (and yes I know how to change oneline) plus making assumptions that turn out to be wrong.

The world audience of the intersection of r-ci and drat may be two.  Maybe it is just one -- @jranke.  So let's not worry about that _as the primary concerrn_.  I built r2u to be reliable and fast.  I like using bspm for it.   I am sorry I have to say this but you are not documenting well how bspm should be used in your eyes.  Can we maybe start by getting bspm ready (as the code appears to be) and maybe document at the bspm repo how you would recommend deployment under different use cases rather than scattering a conversation over three other repos with two other affected users.

**Comment by jranke** [comment]
Hey Dirk, indeed there is no need to worry about myself, I can cope with the workaround. I just thought the issue was resolved (it has been closed as completed), but the behaviour of r-ci described originally is still the same, so we should consider reopening the issue or mark it as wontfix?

**Comment by eddelbuettel** [comment]
@jranke I trust you can, but this is a good example of how @Enchufa2 and I were a little fast and loose and let code out that can have unforeseen consequence.  I am really thankful you brought it up because for every user for whom something may not work -- and who files an issue -- there may always be X more that we do not know about.
