### ISSUE TITLE
Add an option to test with older versions of R

### ISSUE THREAD

**Issue by rubak** [eddelbuettel/r-ci#5]
As we discussed it could be nice with a clear way to test with an older version of R rather than what is current on the given distro with the CRAN/rutter repositories activated. We could layout the ideas in this issue.

**Comment by eddelbuettel** [comment]
As riffed in https://github.com/eddelbuettel/r-ci/issues/3#issuecomment-819470834 it may be tricky.  We can start by decomposing into 
- commands to install an R older that R-release, ideally via `apt`
- commands to install R packages, ideally as binaries

**Comment by rubak** [comment]
I had this working with GitHub Actions by using Ubuntu 18.04 and removing the preinstalled R 4.0. Then setting `R_VERSION="3.5"` installs the latest version with the 3.5 API (which is 3.6.3), and binary install of packages seemed to work fine.

So to get a specific R version you need a compatible Ubuntu, and we need to tell users so. The docs could loosely say:

- R<3.5: Not supported:
- 3.5<=R<4.0: You need Ubuntu {14,16,18}.04, and have to set `R_VERSION="3.5"`. If you set `R_RUNTIME_VERSION = x.x.x` you run R x.x.x (if it exists and satisfies the constraints) otherwise if it is unset you get the latest R version with the API (3.6.3).
- R>=4.0: You need Ubuntu {16,18,20}.04 or 20.10, and have to set `R_VERSION="4.0"`. If you set `R_RUNTIME_VERSION = x.x.x` you run R x.x.x (if it exists and satisfies the constraints) otherwise if unset you get the latest R version with the API (4.0.5 at the time of writing the docs, but will increase as long as the API is unchanged).

Is that goal too ambitious?

**Comment by eddelbuettel** [comment]
I think you running a risk of generalizing from side effects here.

As a _one time switch_ we moved PPAs.  So for one time we can currently point to an old one.  That simply will not generalise to having, say, 4.1 and 4.0 in a few weeks time.

**Comment by eddelbuettel** [comment]
We could take some lessons from this though:

- Someone (you ? me ? us both ?) could set up a new repo 'r-previous' and instead of the main 'CRAN mirror of Michael's PPA for R itself' we point to that.
- If and when R actually remains backwards compatible we can simple point to the Rutter PPA (!!) (though each package load will get the dreaded warning "xyz was compiled under 'R greater than this'".  Do we care?

**Comment by rubak** [comment]
That warning is indeed something that makes newcomers (and partially me) nervous, but I guess we shouldn't care.

Regarding the new repo r-previous I have no idea what to do. I'm happy to help and in particular to test and write docs. Is this repo going to contain things similar to https://cloud.r-project.org/bin/linux/ubuntu/bionic-cran40/ with all R versions from 4.0 and upwards? I'm not sure I understand which parts related to "one time" events and what we can expect and utilize in the future, but you don't have to spend time going through the details if it becomes to tiresome. You usually know what you are doing and I'm happy to roll along and provide some assistance...

**Comment by eddelbuettel** [comment]
It's potentially simpler to setup as we simply _copy_ existing .deb binaries for Ubuntu.  (That said, actually, we could also use Launchpad and just rebuild whatever we need there under the existing preferred 'older' R binary.)

I have two example of informal 'PPA' at GitHub here:
- for the related problem when I update Rocker:  https://github.com/eddelbuettel/ppaR400
- a more general PPA I use for binaries  https://github.com/eddelbuettel/ppa

Those are working examples.  We could follow the same mold, either at Ubuntu / Launchpad (has build infra!) or at GitHub for binaries.  The script to update the PACKAGES{,.gz} files tend to be simple:

```sh
#!/bin/bash
apt-ftparchive packages . > Packages
cat Packages | gzip - > Packages.gz
```

You would have to lead this and learn about packages.  When I say 'Launchpad' it would mean you becoming active there and owning a repo (so that you can trigger builds) to basically shadow what Michael does, with fewer packages and / or just copies.

Just having a web-accessible directory is an easier step.  And for the simplest case we don;t even have to rebuild.  We can just put R 4.0.5 there and use it once R 4.1.0 comes out.  If you desire R 3.6.3 you would have to build that (or find a suitable binary).

It is all "just" connecting dots with a few properly sketched lines. I can help you with hints, but I cannot build it for you.

**Comment by rubak** [comment]
Sorry for the radio silence. We are all busy as you know and say :-)

I still don't quite understand the need for the new repository. At the moment all relevant R versions with the API of 3.5<=R<4.0 are at https://cloud.r-project.org/bin/linux/ubuntu/bionic-cran35/ for 18.04 and at https://cloud.r-project.org/bin/linux/ubuntu/xenial-cran35/ for 16.04:

```
      r-base-core_3.5.0-1xenial_amd64.deb                         2018-04-24 00:10   23M  
      r-base-core_3.5.0-1xenial_i386.deb                          2018-04-24 00:10   23M  
      r-base-core_3.5.1-1xenial_amd64.deb                         2018-07-03 02:29   23M  
      r-base-core_3.5.1-1xenial_i386.deb                          2018-07-03 02:29   23M  
      r-base-core_3.5.1-2xenial_amd64.deb                         2018-11-19 19:16   23M  
      r-base-core_3.5.1-2xenial_i386.deb                          2018-11-19 20:00   23M  
      r-base-core_3.5.2-1xenial_amd64.deb                         2018-12-20 17:39   23M  
      r-base-core_3.5.2-1xenial_i386.deb                          2018-12-20 17:29   23M  
      r-base-core_3.5.3-1xenial_amd64.deb                         2019-03-11 22:26   23M  
      r-base-core_3.5.3-1xenial_i386.deb                          2019-03-11 22:26   23M  
      r-base-core_3.6.0-1xenial_amd64.deb                         2019-04-27 13:53   23M  
      r-base-core_3.6.0-1xenial_i386.deb                          2019-04-27 13:53   23M  
      r-base-core_3.6.0-2xenial_amd64.deb                         2019-05-13 01:28   23M  
      r-base-core_3.6.0-2xenial_i386.deb                          2019-05-13 01:28   23M  
      r-base-core_3.6.1-1xenial_amd64.deb                         2019-07-06 11:49   23M  
      r-base-core_3.6.1-1xenial_i386.deb                          2019-07-06 11:38   23M  
      r-base-core_3.6.1-3xenial_amd64.deb                         2019-07-26 13:23   23M  
      r-base-core_3.6.1-3xenial_i386.deb                          2019-07-26 13:23   23M  
      r-base-core_3.6.2-1xenial_amd64.deb                         2019-12-14 02:41   23M  
      r-base-core_3.6.2-1xenial_i386.deb                          2019-12-14 02:41   23M  
      r-base-core_3.6.3-1xenial_amd64.deb                         2020-02-29 15:45   23M  
      r-base-core_3.6.3-1xenial_i386.deb                          2020-02-29 16:03   23M  
```

Are these repositories going to disappear at some point?

Similarly all R versions with the API of R>=4.0 are available for 18.04 and 20.04. Are these the ones that will disappear when R 4.1 is released? (I see that you already have the alpha version in you own PPA).

Given that we cannot reuse these existing repositories, is one possible solution that I set up something like your https://github.com/eddelbuettel/ppaR400 where I simply copy all the binaries from these CRAN mirrors of Michael's stuff and set up an appropriate `Packages`? And then I need to update this repo with new binaries when new versions of R are released?

**Comment by eddelbuettel** [comment]
As I said, the best next step would be an actual set of executable steps in a simple one-off scripts. 

If an when we can 'hit' the binaries with proper `apt-get install` (or `apt install`) commands we can look into supporting it in `run.sh`.  But first we need the existence proof.  _Maybe_ setting the (desired, know, fixed) version in the call as I do in the Dockerfile for that ppaR400 is all it needs.

**Comment by rubak** [comment]
OK. I will try to make a script. I'll write again here when I have something to show.

**Comment by eddelbuettel** [comment]
I am closing this for inaction now.
