### ISSUE TITLE
Package required but not available: ‘RcppEigen’

### ISSUE THREAD

**Issue by erikcs** [eddelbuettel/r-ci#7]
Hi, this only happens on [Mac](https://dev.azure.com/grf-labs/grf/_build/results?buildId=1526&view=logs&j=e2ca6291-fc4b-5722-7227-8542a33d4313&t=df28747f-c6d7-5d7f-43ed-93bc69c86d7c) and I guess it's because a new `RcppEigen` just landed on CRAN and R-CI is trying to install the binaries, which aren't available yet.

No big deal waiting a few days until OSX binaries are on CRAN then restarting the Azure job, just letting you know in case you want to add a workaround to the the ci script.

**Comment by eddelbuettel** [comment]
Are you regularly running the macOS setup?  I actually ... am not simply because I have so much less visibility into what is available where.  The bspm access to .deb binaries for what I need rules my world and use cases.  And I just don't have that many packages without (at least some) dependencies.

As you just closed the other ticket, I think we can close this too.  There is no actual defiency here in `r-ci` we could do much about, I fear.

**Comment by erikcs** [comment]
Sounds good! Yes I just run MacOS in parallel to Ubuntu to get grf's myriad of statistical test to run on two OS's, if one fails but not the other I know it's just OK sampling variation within acceptable epsilon tolerance

**Comment by eddelbuettel** [comment]
Good to know.  We could probably lean a little on existing actions code but keep it simple and in the r-ci shell script -- the RSPM binaries should generally be there (even if with a little delay).  I haven't been too motivated / too busy with other stuff but if you see shortcoming we can probably get to them.

**Comment by erikcs** [comment]
Sounds good, I'm fine leaving as is and not overcomplicating this!
GRF has so few dependencies that this will rarely cause any issues with the CI
